#!/bin/bash
set -e

if [ "$1" == "--build-reddit-poller" ]; then
  echo "Building Reddit Poller image..."
  cd apps/reddit-poller
  chmod +x build.sh
  ./build.sh
  cd ../..
  echo "Reddit Poller image built and loaded successfully!"
fi

echo "===== STAGE 1: Creating infrastructure and K3s cluster ====="
cd infra/platform
terraform init
terraform apply -auto-approve

# Get outputs from stage 1
if ! MASTER_IP=$(terraform output -raw k3s_master_ip 2>/dev/null); then
  echo "ERROR: Required output 'k3s_master_ip' not found."
  echo "Please ensure your outputs.tf includes the k3s_master_ip output."
  exit 1
fi

if ! WEB_IP=$(terraform output -raw website_floating_ip 2>/dev/null); then
  echo "ERROR: Required output 'website_floating_ip' not found."
  echo "Please ensure your outputs.tf includes the website_floating_ip output."
  exit 1
fi

KUBECONFIG_PATH="kubeconfig.yaml"

echo "Master IP: $MASTER_IP"
echo "Website floating IP: $WEB_IP"
echo "Kubeconfig: $KUBECONFIG_PATH"

echo "Waiting for K3s to stabilize..."
sleep 5

# Safety check - make sure the kubeconfig file exists
if [ ! -f "${KUBECONFIG_PATH}" ]; then
  echo "ERROR: Kubeconfig file not found at ${KUBECONFIG_PATH}"
  echo "Make sure the K3s cluster was created successfully in Stage 1"
  exit 1
fi

# Create a symlink to the kubeconfig in the root directory for convenience
cd ../..
ln -sf infra/platform/${KUBECONFIG_PATH} ${KUBECONFIG_PATH}
echo "Created symlink to kubeconfig at ./${KUBECONFIG_PATH}"

echo "===== STAGE 2: Deploying applications with Helm ====="
cd infra/services

# Pass the dynamic values to terraform
cat > terraform.auto.tfvars <<EOF
# Auto-generated by deploy.sh - $(date)
master_ip = "${MASTER_IP}"
website_floating_ip = "${WEB_IP}"
kubeconfig_path = "../platform/${KUBECONFIG_PATH}"
EOF

terraform init
terraform apply -auto-approve

cd ../..

echo "===== DEPLOYMENT COMPLETE ====="
echo "You can access your cluster using:"
echo "export KUBECONFIG=$(pwd)/${KUBECONFIG_PATH}"
echo "kubectl get nodes"
echo ""
echo "To check all pods:"
echo "KUBECONFIG=$(pwd)/${KUBECONFIG_PATH} kubectl get pods --all-namespaces"
echo ""
echo "To connect to redis inspector:"
echo "kubectl exec -it redis-inspector -n trading -- /bin/sh"
echo "...and view latest events:"
echo "inspect-redis-streams.sh"